language: cpp

sudo: false

os:
 - linux
 - osx

compiler:
 - gcc
 - clang

env:
 -
 - CONFIGURE_FLAGS="--enable-shared"

matrix:
  include:
    - services:
       - docker
      env:
       - DOCKER=i386/ubuntu
    # Newer toolchain
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

addons:
  apt_packages:
      - autoconf
      - automake
      - libtool

install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install ccache && export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

script: ./.travis-build.sh

after_failure:
  - ./.travis-print-logs.sh

cache: ccache
