language: cpp

sudo: false

matrix:
  include:
    - os: linux
      env:
       -
    - os: linux
      env:
      compiler: clang
    - os: osx
      env:
       -
    - services:
      - docker
      env:
       - DOCKER=i386/ubuntu

addons:
  apt_packages:
      - autoconf
      - automake
      - libtool


script: ./.travis-build.sh
